name: super_rocket

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:      


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3



    - name: Download IP files
      run: |
        curl -sSL -o ipv4.conf "https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china.txt"
        curl -sSL -o ipv6.conf "https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china6.txt"


    - name: Generate ip.conf
      run: |
        sed -i 's/^/IP-CIDR,/' ipv4.conf
        sed -i 's/$/,DIRECT/'  ipv4.conf

        sed -i 's/^/IP-CIDR,/' ipv6.conf
        sed -i 's/$/,DIRECT/'  ipv6.conf

        cat ipv4.conf >> ip.conf
        cat ipv6.conf >> ip.conf

    - name: Generate cn_domains.conf    
      run: |
        curl -sSL -o cn_domains https://raw.githubusercontent.com/viaten/cn_domain_names/main/data/accelerated-domains.china
        sed -i 's/^/DOMAIN-SUFFIX,/' cn_domains
        sed -i 's/$/,DIRECT/'  cn_domains
        mv cn_domains cn_domains.conf

    - name: Generate ad_doamins.conf    
      run: |
        curl -sSL -o ad_domains https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt
        sed -i 's/^/DOMAIN-SUFFIX,/' ad_domains
        sed -i 's/$/,REJECT/'  ad_domains
        mv ad_domains ad_domains.conf

    - name: Generate gfwlist_doamins.conf    
      run: |
        curl -sSL -k https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt |base64 -d |sed -n '{s/^||\?//g;s/https\?:\/\///g;s/^\.//g;s/\*.*//g;s/\/.*//g;s/%.*//g;/^$/d;/^!.*/d;/^@.*/d;/^\[.*/d;/\.$/d;/^[^\.]*$/d;/^[0-9\.]*$/d;p}' |sort |uniq
        sed -i 's/^/DOMAIN-SUFFIX,/' gfwlist.txt
        sed -i 's/$/,proxy/'  gfwlist.txt
        mv gfwlist.txt gfwlist.conf
 


    - name: final files
      run: |
        echo "##update date: $(date +%Y%m%d%H%M%S)" >> base.conf
        echo "[General]" >> base.conf
        echo "bypass-system = true" >> base.conf
        echo "skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local" >> base.conf
        echo "bypass-tun = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32" >> base.conf
        echo "dns-server = system" >> base.conf
        echo "[Rule]" >> base.conf
        echo "DOMAIN-KEYWORD,ocsp,REJECT-DROP" >> base.conf
        cat gfwlist.conf ad_domains.conf cn_domains.conf ip.conf >> base.conf

        cp base.conf whitelist.conf
        echo "FINAL,proxy" >> whitelist.conf
        cp base.conf blacklist.conf
        echo "FINAL,direct" >> blacklist.conf
        
        if [ ! -d "data/super_rocket" ]; then mkdir data/super_rocket; fi
        mv whitelist.conf data/super_rocket/
        mv blacklist.conf data/super_rocket/






    - name: Commit file
      run: |
        git config --global user.name "dummyuser"
        git config --global user.email "dummyuser@github.com"
        git add  data/super_rocket
        git commit -m "super_rocket $(date +%Y%m%d%H%M%S)"
        git push origin main
